import type { DailyRoutineTask } from "./tasks.types";

export const dailyRoutineTasks: DailyRoutineTask[] = [
  {
    id: "task-001",
    name: "Wake Up",
    taskType: "check",
    frequency: "daily",
    streak: 12,
    isDoneToday: true,
    taskStatus: "done",
  },
  {
    id: "task-002",
    name: "Brush Teeth",
    taskType: "check",
    frequency: "daily",
    streak: 18,
    isDoneToday: true,
    taskStatus: "done",
  },
  {
    id: "task-003",
    name: "Take a Bath",
    taskType: "check",
    frequency: "daily",
    streak: 9,
    isDoneToday: false,
    taskStatus: "pending",
  },
  {
    id: "task-004",
    name: "Morning Tea",
    taskType: "check",
    frequency: "daily",
    streak: 21,
    isDoneToday: false,
    taskStatus: "pending",
  },
  {
    id: "task-005",
    name: "Read a Book",
    taskType: "session",
    frequency: "daily",
    streak: 7,
    isDoneToday: false,
    startTime: "08:00",
    endTime: "09:00",
    taskStatus: "in-progress",
    sessionDuration: 60,
  },
  {
    id: "task-006",
    name: "Breakfast",
    taskType: "check",
    frequency: "daily",
    streak: 15,
    isDoneToday: false,
    taskStatus: "pending",
  },
  {
    id: "task-007",
    name: "Deep Work",
    taskType: "session",
    frequency: "daily",
    streak: 5,
    isDoneToday: false,
    startTime: "10:00",
    endTime: "14:00",
    taskStatus: "pending",
    sessionDuration: 240,
  },
  {
    id: "task-008",
    name: "Lunch",
    taskType: "check",
    frequency: "daily",
    streak: 11,
    isDoneToday: false,
    taskStatus: "pending",
  },
  {
    id: "task-009",
    name: "Study Computer Science",
    taskType: "session",
    frequency: "daily",
    streak: 14,
    isDoneToday: false,
    startTime: "15:00",
    endTime: "17:00",
    taskStatus: "paused",
    sessionDuration: 120,
  },
  {
    id: "task-010",
    name: "Evening Tea",
    taskType: "check",
    frequency: "daily",
    streak: 20,
    isDoneToday: false,
    taskStatus: "pending",
  },
  {
    id: "task-011",
    name: "Gaming",
    taskType: "session",
    frequency: "daily",
    streak: 4,
    isDoneToday: false,
    startTime: "18:00",
    endTime: "20:00",
    taskStatus: "pending",
    sessionDuration: 120,
  },
  {
    id: "task-012",
    name: "English Practice",
    taskType: "session",
    frequency: "daily",
    streak: 16,
    isDoneToday: false,
    startTime: "20:15",
    endTime: "20:45",
    taskStatus: "pending",
    sessionDuration: 30,
  },
  {
    id: "task-013",
    name: "Dinner",
    taskType: "check",
    frequency: "daily",
    streak: 13,
    isDoneToday: false,
    taskStatus: "pending",
  },
  {
    id: "task-014",
    name: "Plan Tomorrow",
    taskType: "check",
    frequency: "daily",
    streak: 3,
    isDoneToday: false,
    taskStatus: "pending",
  },
  {
    id: "task-015",
    name: "Sleep",
    taskType: "check",
    frequency: "daily",
    streak: 6,
    isDoneToday: false,
    taskStatus: "pending",
  },
];
